apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "access-tracker.fullname" . }}
  labels:
    {{- include "access-tracker.labels" . | nindent 4 }}
data:
  GRAPHQL_ENDPOINT: "http://{{ include "access-tracker.fullname" . }}-backend:{{ .Values.backend.port }}/graphql"
