{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "access-tracker.fullname" . }}
  labels:
    {{- include "access-tracker.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.clusterIssuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ include "access-tracker.fullname" . }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "access-tracker.fullname" . }}-backend
                port:
                  number: {{ .Values.service.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "access-tracker.fullname" . }}-frontend
                port:
                  number: {{ .Values.service.frontend.port }}
{{- end }}
