backend:
  image: quay.io/mathianasj/access-tracker-server:latest
  replicaCount: 1
  pullPolicy: Always
  port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

frontend:
  image: quay.io/mathianasj/access-tracker-frontend:latest
  replicaCount: 1
  pullPolicy: Always
  port: 80
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

postgresql:
  enabled: true
  auth:
    database: access_tracker
    username: access_tracker_dev
    password: ""
  primary:
    persistence:
      enabled: false
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

service:
  backend:
    port: 8080
    type: ClusterIP
  frontend:
    port: 80
    type: ClusterIP

ingress:
  enabled: true
  className: nginx
  host: dev.access-tracker.local
  tls:
    enabled: false

autoscaling:
  enabled: false
